### ISSUE TITLE
Marker Displayer is broken

### ISSUE THREAD

**Issue by sammyjava** [LegumeFederation/intermine-soymine#2]
```
org.intermine.objectstore.ObjectStoreException: PathQuery is invalid: [Path GeneticMarker.mappingPopulations.primaryIdentifier in view list is not in the model, Path GeneticMarker.mappingPopulations.primaryIdentifier in order by list is not in the model]
	at org.intermine.api.query.MainHelper.makeQuery(MainHelper.java:133)
	at org.intermine.api.query.PathQueryExecutor.makeQuery(PathQueryExecutor.java:156)
	at org.intermine.api.query.PathQueryExecutor.execute(PathQueryExecutor.java:96)
	at org.ncgr.intermine.bio.web.displayer.MarkerDisplayer.getResults(MarkerDisplayer.java:109)
	at org.ncgr.intermine.bio.web.displayer.MarkerDisplayer.display(MarkerDisplayer.java:64)
	at org.intermine.web.displayer.ReportDisplayer.execute(ReportDisplayer.java:62)
	at org.intermine.web.struts.ReportDisplayerController.execute(ReportDisplayerController.java:43)
	at org.intermine.web.struts.ModifyDetails.ajaxShowDisplayer(ModifyDetails.java:296)
	at sun.reflect.GeneratedMethodAccessor383.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:269)
	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:170)
	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
	at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.intermine.web.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:139)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:877)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2521)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2510)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sammyjava** [comment]
Explanation: Markers haven't been associated with mapping populations in SoyMine. They shouldn't have to be.

**Comment by sammyjava** [comment]
Oh. Not a bug - we don't have genotyping matrices for Soybean.
